### ISSUE TITLE
socket.io-emitter security vulnerability

### ISSUE THREAD

**Issue by skhilliard** [socketio/socket.io-redis-emitter#102]
There is a security vulnerability for the socket.io-parser (3.1.2) dependency for the latest version socket.io-emitter (3.2.0):
[https://www.npmjs.com/advisories/1763](url)

Can this dependency be updated to fix this vulnerability?

**Comment by darrachequesne** [comment]
Hi! You should be able to migrate to `@socket.io/redis-emitter` (the `socket.io-emitter` package has been renamed), which does not suffer from this issue. Could you please check?

**Comment by skhilliard** [comment]
Thanks!  That solved the issue...I was able to migrate to @socket.io/redis-emitter.
