### ISSUE TITLE
Severity issues: high

### ISSUE THREAD

**Issue by hacsterLite** [socketio/socket.io-redis-emitter#105]
node_modules/socket.io-emitter/node_modules/socket.io-parser uses ~4.0.4 need 4.1.1
https://github.com/advisories/GHSA-xfhh-g9f5-x4m4

node_modules/socket.io-emitter/node_modules/redis uses 3.0.2 need 3.1.2
https://github.com/advisories/GHSA-35q2-47q7-3pc3

**Comment by darrachequesne** [comment]
Hi! Which version of `@socket.io/redis-emitter` is impacted?

**Comment by hacsterLite** [comment]
Yes, sorry 
I used outdated `socket.io-redis-emitter` not `@socket.io/redis-emitter `
:(

after upgrade all's fine 🌈
