### ISSUE TITLE
Namespace - Typed Events

### ISSUE THREAD

**Issue by tada5hi** [socketio/socket.io-redis-emitter#107]
When you try to emit events to a specific namespace, the EventsMap which is possibly defined for the root Emitter instance, is not applied for the Emitter instance returned by the `of` method.

**Comment by tada5hi** [comment]
Would be really great if this could be available soon 😊. It is a bit annoying, to cast the return value of the `of` method, to have typed event support for namespaces 😅.

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/socket.io-redis-emitter/commit/53c73e11661067b30cafa8f33a7ec0a61dcbd431, included in `@socket.io/redis-emitter@4.1.1`. Thanks!

**Comment by tada5hi** [comment]
Your welcome 🤗, have a nice week.
