### ISSUE TITLE
Rename to socket.io-redis-emitter

### ISSUE THREAD

**Issue by MickL** [socketio/socket.io-redis-emitter#94]
This emitter is tied to redis and should be named accordingly, imo.

**Comment by darrachequesne** [comment]
Done! The package is now called `@socket.io/redis-emitter` (https://github.com/socketio/socket.io-emitter/commit/592883e9d85063411ffde760e0cdef10245e2573)

I'll ask the team at Automattic to rename the repository.

**Comment by darrachequesne** [comment]
Done! The repository is now called https://github.com/socketio/socket.io-redis-emitter
