### ISSUE TITLE
Send a message to the room, why can you receive it if you are not in this room?

### ISSUE THREAD

**Issue by einsqing** [socketio/socket.io-redis-emitter#97]
Send a message to the room, why can you receive it if you are not in this room?

    "socket.io": "^4.0.0",
    "socket.io-client": "^4.0.0",
    "socket.io-emitter": "^3.2.0",
    "socket.io-redis": "^6.1.0",

io.to(sid).emit('hello', "to all clients in 'room42' room except sender");

**Comment by darrachequesne** [comment]
Closed as duplicate of https://github.com/socketio/socket.io-redis/issues/394.
